# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_catgory'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='courese_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
