# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(default='web后台', max_length=300, verbose_name='课程类型'),
        ),
    ]
